//
//  RoutineExercise.swift
//  fitbod
//
//  Per-exercise prescription within a Routine template. Each field on this
//  type has a mirror on `SessionExercise` — when a Session starts, the
//  values are *copied* (not referenced), so editing the template tomorrow
//  never rewrites yesterday's logged session. This is the load-bearing
//  snapshot field set per PITFALLS #1 — the field set must exist Day 1
//  even though Phase 2 owns the snapshot logic.
//
//  Enum-backed fields persist as `*Raw: String` with computed accessors in
//  the extension below (FOUND-03 / PITFALLS #9).
//
//  `generateWarmups: Bool = false` defaults to off; the routine builder
//  in Phase 2 flips it on for the first compound by convention. Per-set
//  warmup actually materialize as SetEntry rows with `isWarmup = true`
//  generated by `WarmupGenerator` in Phase 3.
//

import Foundation
import SwiftData

@Model
public final class RoutineExercise {
    @Attribute(.unique) public var id: UUID = UUID()
    public var routine: Routine? = nil
    public var exercise: Exercise? = nil
    public var orderIndex: Int = 0

    public var intentRaw: String = "hypertrophy"
    public var targetSets: Int = 3
    public var targetRepsLow: Int = 8
    public var targetRepsHigh: Int = 12
    public var targetRPE: Double? = nil
    public var targetRIR: Int? = nil
    public var prescribedRestSeconds: Int = 120
    public var tempo: String? = nil
    public var notes: String? = nil
    public var progressionKindRaw: String = "double"
    public var generateWarmups: Bool = false
    public var supersetGroupID: UUID? = nil
    public var tracksTempo: Bool = false
    public var tracksPartialReps: Bool = false
    public var warmupOverrideData: Data? = nil

    @Relationship(deleteRule: .cascade, inverse: \RoutineExerciseSetOverride.routineExercise)
    public var setOverrides: [RoutineExerciseSetOverride]? = []

    public init() {}
}

extension RoutineExercise {
    public var intent: Intent { Intent(rawValue: intentRaw) ?? .hypertrophy }
    public var progressionKind: ProgressionKind {
        ProgressionKind(rawValue: progressionKindRaw) ?? .double
    }
    public var warmupOverride: WarmupConfig? {
        get {
            guard let data = warmupOverrideData else { return nil }
            return try? JSONDecoder().decode(WarmupConfig.self, from: data)
        }
        set {
            warmupOverrideData = try? JSONEncoder().encode(newValue)
        }
    }
}
